/*
   Copyright The containerd Authors.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

package erofsutils

import (
	"context"
	"crypto/rand"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/containerd/containerd/v2/core/mount"
	"github.com/containerd/containerd/v2/internal/dmverity"
	"github.com/containerd/errdefs"
	"github.com/containerd/log"
)

// VerityMode specifies how to store dm-verity data
type VerityMode int

const (
	// VerityModeSeparate stores data and hash tree in separate files
	VerityModeSeparate VerityMode = iota
	// VerityModeCombined combines data and hash tree in a single file
	VerityModeCombined
)

// VerityConfig contains dm-verity configuration
type VerityConfig struct {
	Enabled      bool
	HashAlgo     string
	RootHash     string
	VerityBlocks int64
	Mode         VerityMode
}

func ConvertTarErofs(ctx context.Context, r io.Reader, layerPath string, mkfsExtraOpts []string) error {
	args := append([]string{"--tar=f", "--aufs", "--quiet", "-Enoinline_data"}, mkfsExtraOpts...)
	args = append(args, layerPath)
	cmd := exec.CommandContext(ctx, "mkfs.erofs", args...)
	cmd.Stdin = r
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("erofs apply failed: %s: %w", out, err)
	}
	log.G(ctx).Infof("running %s %s %v", cmd.Path, cmd.Args, string(out))
	return nil
}

func ConvertErofs(ctx context.Context, layerPath string, srcDir string, mkfsExtraOpts []string) error {
	args := append([]string{"--quiet", "-Enoinline_data"}, mkfsExtraOpts...)
	args = append(args, layerPath, srcDir)
	cmd := exec.CommandContext(ctx, "mkfs.erofs", args...)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("erofs apply failed: %s: %w", out, err)
	}
	log.G(ctx).Infof("running %s %s %v", cmd.Path, cmd.Args, string(out))
	return nil
}

// ConvertErofsWithVerity converts a directory to EROFS format with dm-verity
func ConvertErofsWithVerity(ctx context.Context, layerPath string, srcDir string, verity VerityConfig, mkfsExtraOpts []string) error {
	if !verity.Enabled {
		return ConvertErofs(ctx, layerPath, srcDir, mkfsExtraOpts)
	}

	// Create EROFS image first
	if err := ConvertErofs(ctx, layerPath, srcDir, mkfsExtraOpts); err != nil {
		return err
	}

	// Get file size for verity setup
	fi, err := os.Stat(layerPath)
	if err != nil {
		return err
	}
	dataSize := fi.Size()
	dataBlocks := (dataSize + dmverity.DefaultBlockSize - 1) / dmverity.DefaultBlockSize

	// Configure dm-verity
	config := dmverity.VerityConfig{
		Version:       1,
		HashAlgorithm: dmverity.HashAlgoSHA256,
		DataBlockSize: dmverity.DefaultBlockSize,
		HashBlockSize: dmverity.DefaultBlockSize,
		DataBlocks:    uint64(dataBlocks),
		Salt:          make([]byte, dmverity.DefaultSaltSize),
	}

	// Generate random salt
	if _, err := rand.Read(config.Salt); err != nil {
		return fmt.Errorf("failed to generate salt: %w", err)
	}

	hashDevice := ""
	if verity.Mode != VerityModeCombined {
		hashDevice = layerPath + ".verity"
	} else {
		// Get data device size for hash offset
		fi, err := os.Stat(layerPath)
		if err != nil {
			return err
		}
		offset := fi.Size()
		config.HashOffset = offset
		hashDevice = layerPath // Use same device for combined mode
	}

	// Generate hash tree and get root hash
	hashTree, rootHash, err := dmverity.GenerateHashTree(layerPath, config)
	if err != nil {
		return fmt.Errorf("failed to enable dm-verity: %w", err)
	}
	config.RootDigest = rootHash

	// Write hash tree if in separate mode
	if verity.Mode != VerityModeCombined {
		if err := os.WriteFile(hashDevice, hashTree, 0644); err != nil {
			return fmt.Errorf("failed to write hash tree: %w", err)
		}
	}

	// Store root hash in verity config
	verity.RootHash = fmt.Sprintf("%x", rootHash)
	return nil
}

// Get the snapshot layer directory in order to generate EROFS-formatted blobs;
//
// If mount[0].Type is `bind` or `erofs`, it just tries the source dir; Or if
// mount[0].Type is `overlayfs`, it tries the parent of the upperdir;
//
// The candidate will be checked with ".erofslayer" to make sure this active
// snapshot is really generated by the EROFS snapshotter instead of others.
func MountsToLayer(mounts []mount.Mount) (string, error) {
	var layer string
	mnt := mounts[0]
	if mnt.Type == "bind" || mnt.Type == "erofs" {
		layer = filepath.Dir(mnt.Source)
	} else if mnt.Type == "overlay" {
		layer = ""
		for _, o := range mnt.Options {
			if strings.HasPrefix(o, "upperdir=") {
				layer = filepath.Dir(strings.TrimPrefix(o, "upperdir="))
			}
		}
		if layer == "" {
			return "", fmt.Errorf("unsupported overlay layer for erofs differ: %w", errdefs.ErrNotImplemented)
		}
	} else {
		return "", fmt.Errorf("invalid filesystem type for erofs differ: %w", errdefs.ErrNotImplemented)
	}
	// If the layer is not prepared by the EROFS snapshotter, fall back to the next differ
	if _, err := os.Stat(filepath.Join(layer, ".erofslayer")); err != nil {
		return "", fmt.Errorf("mount layer type must be erofs-layer: %w", errdefs.ErrNotImplemented)
	}
	return layer, nil
}
